name: Build and Push DDOS-Base Builder

# Запускаем на каждый пуш в main
on:
  push:
    branches: [ main ]

permissions:
  contents: read    # для checkout
  packages: write   # для пуша образов в GHCR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 👷 Checkout code
        uses: actions/checkout@v4

      - name: 🔐 Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏗️ Build builder stage
        run: |
          docker build \
            --target builder \
            -t ghcr.io/DeDnY/ha-ddos-builder:latest \
            .

      - name: 📤 Push builder image
        run: |
          docker push ghcr.io/<ВАШ_ЛОГИН>/ha-ddos-builder:latest

      - name: ✅ Test final add-on build
        run: |
          docker build \
            --build-arg BUILD_FROM=ghcr.io/DeDnY/ha-ddos-builder:latest \
            -t local/ha-ddos-addon:latest \
            .
