name: "DDoS Protection"
version: "3.5"
slug: "ddos_protection"
description: "Protect Home Assistant from DDoS and BruteForce"

arch:
  - aarch64
  - amd64
  - armv7

startup: application
boot: auto
host_network: true

privileged:
  - NET_ADMIN
  - NET_RAW

webui: "http://[HOST]:[PORT:8080]"

map:
  config: /config

options:
  ddos_threshold: 600
  max_retry: 10
  ban_time: 600

schema:
  ddos_threshold: "int"
  max_retry: "int"
  ban_time: "int"
